@extends('layouts.custom')

@section('content')
<div class="max-w-4xl mx-auto space-y-6">
    <!-- Header -->
    <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6">
        <div class="flex justify-between items-center">
            <div>
                <h1 class="text-3xl font-bold text-gray-900">Kalender Ketersediaan</h1>
                <p class="text-gray-600 mt-2">{{ $car->name }} ({{ $car->brand }})</p>
            </div>
            <a href="{{ route('cars.show', $car) }}" class="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 transition">
                ← Kembali ke Detail
            </a>
        </div>
    </div>

    <!-- Calendar -->
    <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6">
        <div id="calendar" class="calendar-container">
            <!-- Calendar will be generated by JavaScript -->
        </div>
    </div>

    <!-- Legend -->
    <div class="bg-white rounded-3xl shadow-sm border border-gray-100 p-6">
        <h3 class="text-lg font-semibold text-gray-900 mb-4">Keterangan</h3>
        <div class="flex flex-wrap gap-4">
            <div class="flex items-center">
                <div class="w-4 h-4 bg-green-200 rounded mr-2"></div>
                <span class="text-sm text-gray-600">Tersedia</span>
            </div>
            <div class="flex items-center">
                <div class="w-4 h-4 bg-red-200 rounded mr-2"></div>
                <span class="text-sm text-gray-600">Sudah dipesan (pending/approved)</span>
            </div>
            <div class="flex items-center">
                <div class="w-4 h-4 bg-blue-200 rounded mr-2"></div>
                <span class="text-sm text-gray-600">Tanggal Dipilih</span>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const calendarContainer = document.getElementById('calendar');
    const viewDate = new Date();
    let selectedStartDate = null;
    let selectedEndDate = null;

    function formatDateLocal(date) {
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    // Unavailable dates from PHP (pending + approved).
    const bookedDates = @json($bookings->map(function($booking) {
        $dates = [];
        $start = \Carbon\Carbon::parse($booking->start_date);
        $end = \Carbon\Carbon::parse($booking->end_date);
        
        for ($date = $start; $date->lte($end); $date->addDay()) {
            $dates[] = $date->format('Y-m-d');
        }
        return $dates;
    })->flatten()->unique()->values()->all());

    const todayStr = formatDateLocal(new Date());

    function generateCalendar(year, month) {
        const firstDay = new Date(year, month, 1);
        const startDate = new Date(firstDay);
        startDate.setDate(startDate.getDate() - firstDay.getDay());

        let html = '<div class="calendar">';
        html += '<div class="calendar-header">';
        html += '<button id="prevMonth" class="calendar-nav">&lt;</button>';
        html += '<h2>' + firstDay.toLocaleDateString('id-ID', { month: 'long', year: 'numeric' }) + '</h2>';
        html += '<button id="nextMonth" class="calendar-nav">&gt;</button>';
        html += '</div>';
        
        html += '<div class="calendar-grid">';
        const daysOfWeek = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
        daysOfWeek.forEach(day => {
            html += '<div class="calendar-day-header">' + day + '</div>';
        });

        let cursorDate = new Date(startDate);
        for (let i = 0; i < 42; i++) {
            const dateStr = formatDateLocal(cursorDate);
            const isCurrentMonth = cursorDate.getMonth() === month;
            const isToday = dateStr === todayStr;
            const isBooked = bookedDates.includes(dateStr);
            const isPast = cursorDate < new Date() && !isToday;
            const isSelected = (selectedStartDate && dateStr === selectedStartDate) || 
                             (selectedEndDate && dateStr === selectedEndDate) ||
                             (selectedStartDate && selectedEndDate && dateStr > selectedStartDate && dateStr < selectedEndDate);

            let className = 'calendar-day';
            if (!isCurrentMonth) className += ' other-month';
            if (isToday) className += ' today';
            if (isBooked) className += ' booked';
            if (isPast) className += ' past';
            if (isSelected) className += ' selected';

            const title = isBooked ? 'Tanggal ini sudah dibooking user lain' : '';
            html += '<div class="' + className + '" data-date="' + dateStr + '" title="' + title + '">' + cursorDate.getDate() + '</div>';
            cursorDate.setDate(cursorDate.getDate() + 1);
        }
        
        html += '</div>';
        html += '</div>';
        
        calendarContainer.innerHTML = html;

        // Add event listeners
        document.getElementById('prevMonth').addEventListener('click', function() {
            viewDate.setMonth(viewDate.getMonth() - 1);
            generateCalendar(viewDate.getFullYear(), viewDate.getMonth());
        });
        
        document.getElementById('nextMonth').addEventListener('click', function() {
            viewDate.setMonth(viewDate.getMonth() + 1);
            generateCalendar(viewDate.getFullYear(), viewDate.getMonth());
        });
    }

    generateCalendar(viewDate.getFullYear(), viewDate.getMonth());
});
</script>

<style>
.calendar-container {
    font-family: Arial, sans-serif;
}

.calendar {
    max-width: 800px;
    margin: 0 auto;
}

.calendar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
}

.calendar-header h2 {
    margin: 0;
    font-size: 24px;
    color: #1f2937;
}

.calendar-nav {
    background: #3b82f6;
    color: white;
    border: none;
    padding: 10px 15px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
}

.calendar-nav:hover {
    background: #2563eb;
}

.calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 2px;
    background: #e5e7eb;
    border-radius: 8px;
    overflow: hidden;
}

.calendar-day, .calendar-day-header {
    background: white;
    padding: 15px 10px;
    text-align: center;
    font-weight: 500;
}

.calendar-day-header {
    background: #f9fafb;
    font-weight: 600;
    color: #374151;
    padding: 10px;
}

.calendar-day {
    cursor: pointer;
    transition: all 0.2s;
    min-height: 50px;
    display: flex;
    align-items: center;
    justify-content: center;
}

.calendar-day:hover:not(.past):not(.booked) {
    background: #dbeafe;
}

.calendar-day.today {
    background: #fef3c7;
    font-weight: bold;
}

.calendar-day.booked {
    background: #fecaca;
    color: #991b1b;
    cursor: not-allowed;
}

.calendar-day.selected {
    background: #bfdbfe;
    color: #1e40af;
    font-weight: bold;
}

.calendar-day.other-month {
    color: #9ca3af;
}

.calendar-day.past:not(.today) {
    color: #d1d5db;
    cursor: not-allowed;
}
</style>
@endsection
